// AUTH
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const USER_CREATED = 'USER_CREATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_USER_LOADING = 'SIGN_UP_USER_LOADING';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// CAR REGISTERATION
export const GET_ALL_VEHICLES = 'GET_ALL_VEHICLES';
export const GET_ALL_VEHICLES_LOADING = 'GET_ALL_VEHICLES_LOADING';
export const REGISTER_VEHICLE = 'REGISTER_VEHICLE';
export const REGISTER_VEHICLE_LOADING = 'REGISTER_VEHICLE_LOADING';
export const PLACE_VEHICLE_ORDER = 'PLACE_VEHICLE_ORDER';
export const PLACE_VEHICLE_ORDER_LOADING = 'PLACE_VEHICLE_ORDER_LOADING';
export const TRANSFER_VEHICLE = 'TRANSFER_VEHICLE';
export const TRANSFER_VEHICLE_LOADING = 'TRANSFER_VEHICLE_LOADING';
export const GET_USER_VEHICLE_ORDERS = 'GET_USER_VEHICLE_ORDERS';
export const GET_USER_VEHICLE_ORDERS_LOADING = 'GET_USER_VEHICLE_ORDERS_LOADING';
export const PLACE_LISCENCE_ORDER = 'PLACE_LISCENCE_ORDER';
export const PLACE_LISCENCE_ORDER_LOADING = 'PLACE_LISCENCE_ORDER_LOADING';
export const GET_ALL_TRANSFER_REQUEST_USER_LOADING = 'GET_ALL_TRANSFER_REQUEST_USER_LOADING';
export const GET_ALL_TRANSFER_REQUEST_USER = 'GET_ALL_TRANSFER_REQUEST_USER';
export const TRANSFER_REQUETS_DATA = 'TRANSFER_REQUETS_DATA';
export const APPROVE_USER_TRANSFER_REQUESTS = 'APPROVE_USER_TRANSFER_REQUESTS';
export const APPROVE_USER_TRANSFER_REQUESTS_LOADING = 'APPROVE_USER_TRANSFER_REQUESTS_LOADING';
export const REJECT_USER_TRANSFER_REQUESTS = 'REJECT_USER_TRANSFER_REQUESTS';
export const REJECT_USER_TRANSFER_REQUESTS_LOADING = 'REJECT_USER_TRANSFER_REQUESTS_LOADING';
export const GET_ALL_USER_TRANSACTIONS = 'GET_ALL_USER_TRANSACTIONS';
export const GET_ALL_USER_TRANSACTIONS_LOADING = 'GET_ALL_USER_TRANSACTIONS_LOADING';
export const GET_ALL_TRANSACTION_DETAILS = 'GET_ALL_TRANSACTION_DETAILS';
export const GET_ALL_TRANSACTION_DETAILS_LOADING = 'GET_ALL_TRANSACTION_DETAILS_LOADING';
export const GET_VEHICLE_TRANSACTION = 'GET_VEHICLE_TRANSACTION';
export const GET_VEHICLE_TAKAFUL_RECORD = 'GET_VEHICLE_TAKAFUL_RECORD';
export const GET_VEHICLE_FAHAS_RECORD = 'GET_VEHICLE_FAHAS_RECORD';
export const GET_LICENSES_USER='GET_LICENSES_USER';
export const GET_LICENSES_USER_LOADING='GET_LICENSES_USER_LOADING';
// CAR MANUFACTURER

export const GET_ALL_VEHICLES_ORDERS_MANUFACTURER = 'GET_ALL_VEHICLES_ORDERS_MANUFACTURER';
export const GET_ALL_VEHICLES_ORDERS_MANUFACTURER_LOADING = 'GET_ALL_VEHICLES_ORDERS_MANUFACTURER_LOADING';
export const UPDATE_VEHICLE_ORDERS_STATUS_MANUFACTURER = 'UPDATE_VEHICLE_ORDERS_STATUS_MANUFACTURER';
export const UPDATE_VEHICLE_ORDERS_STATUS_MANUFACTURER_LOADING = 'UPDATE_VEHICLE_ORDERS_STATUS_MANUFACTURER_LOADING';
export const GET_ALL_MANUFACTURER = 'GET_ALL_MANUFACTURER';
export const GET_ALL_MANUFACTURER_LOADING = 'GET_ALL_MANUFACTURER_LOADING';
export const GET_ALL_MANUFACTURER_TRANSACTIONS = 'GET_ALL_MANUFACTURER_TRANSACTIONS';
export const GET_ALL_MANUFACTURER_TRANSACTIONS_LOADING = 'GET_ALL_MANUFACTURER_TRANSACTIONS_LOADING';

// MINISTORY
export const GET_ALL_TRANSFER_REQUESTS = 'GET_ALL_TRANSFER_REQUESTS';
export const GET_ALL_TRANSFER_REQUESTS_LOADING = 'GET_ALL_TRANSFER_REQUESTS_LOADING';
export const APPROVE_TRANSFER_REQUESTS = 'APPROVE_TRANSFER_REQUESTS';
export const APPROVE_TRANSFER_REQUESTS_LOADING = 'APPROVE_TRANSFER_REQUESTS_LOADING';
export const GET_ALL_LISCENCE_ORDERS = 'GET_ALL_LISCENCE_ORDERS';
export const GET_ALL_LISCENCE_ORDERS_LOADING = 'GET_ALL_LISCENCE_ORDERS_LOADING';
export const GET_ALL_LISCENCE = 'GET_ALL_LISCENCE';
export const GET_ALL_LISCENCE_LOADING = 'GET_ALL_LISCENCE_LOADING';
export const GET_ALL_MINISTORY = 'GET_ALL_MINISTORY';
export const UPDATE_LICENCE_ORDER_STATUS = 'UPDATE_LICENCE_ORDER_STATUS';
export const UPDATE_LICENCE_ORDER_STATUS_LOADING = 'UPDATE_LICENCE_ORDER_STATUS_LOADING';
export const GET_UNAPPROVED_VEHICLES = 'GET_UNAPPROVED_VEHICLES';
export const GET_UNAPPROVED_VEHICLES_LOADING = 'GET_UNAPPROVED_VEHICLES_LOADING';
export const APPROVE_VEHICLE = 'APPROVE_VEHICLE';
export const APPROVE_VEHICLE_LOADING = 'APPROVE_VEHICLE_LOADING';
export const GET_ALL_MINISTORY_TRANSACTIONS = 'GET_ALL_MINISTORY_TRANSACTIONS';
export const GET_ALL_MINISTORY_TRANSACTIONS_LOADING = 'GET_ALL_MINISTORY_TRANSACTIONS_LOADING';
export const GET_ALL_VEHICLE = 'GET_ALL_VEHICLE';
export const GET_ALL_VEHICLE_LOADING = 'GET_ALL_VEHICLE_LOADING';
  
//FAHAS
export const GET_ALL_FAHAS_DATA = 'GET_ALL_FAHAS_DATA';
export const GET_ALL_FAHAS_DATA_LOADING = 'GET_ALL_FAHAS_DATA_LOADING';
export const GET_ALL_FAHAS_VEHICLES = 'GET_ALL_FAHAS_VEHICLES';
export const GET_ALL_FAHAS_VEHICLES_LOADING = 'GET_ALL_FAHAS_VEHICLES_LOADING';
export const ADD_FAHAS_RECORD_LOADING = 'ADD_FAHAS_RECORD_LOADING';
export const GET_ALL_FAHAS_TRANSACTIONS = 'GET_ALL_FAHAS_TRANSACTIONS';
export const GET_ALL_FAHAS_TRANSACTIONS_LOADING = 'GET_ALL_FAHAS_TRANSACTIONS_LOADING';

//TAKAFUL
export const GET_ALL_TAKAFUL_DATA = 'GET_ALL_TAKAFUL_DATA';
export const GET_ALL_TAKAFUL_DATA_LOADING = 'GET_ALL_TAKAFUL_DATA_LOADING';
export const GET_ALL_TAKAFUL_VEHICLES = 'GET_ALL_TAKAFUL_VEHICLES';
export const GET_ALL_TAKAFUL_VEHICLES_LOADING = 'GET_ALL_TAKAFUL_VEHICLES_LOADING';
export const ADD_TAKAFUL_RECORD_LOADING = 'ADD_TAKAFUL_RECORD_LOADING';
export const GET_ALL_TAKAFUL_TRANSACTIONS = 'GET_ALL_TAKAFUL_TRANSACTIONS';
export const GET_ALL_TAKAFUL_TRANSACTIONS_LOADING = 'GET_ALL_TAKAFUL_TRANSACTIONS_LOADING';
